Initial Commit
Zummit-Africa-Inc/Web-Page-FE pull request #56
Opened 2022-07-29 08:05 UTC by Vinyl-Davyl

2022-07-29 08:53 UTC, pablo-clueless approved these changes

2022-07-30 21:37 UTC, taiwoAkindele requested changes

2022-07-30 21:37 UTC, taiwoAkindele commented on src/components/PaystackIntegration.jsx
> -        setAmount(res.data.data[0].price)
Why did you delete this? We are getting the price from here.

2022-07-30 21:37 UTC, taiwoAkindele commented on src/components/PaystackIntegration.jsx
> +                      value={firstName}
Value should be `LastName`

2022-07-30 21:37 UTC, taiwoAkindele commented on src/components/PaystackIntegration.jsx
> +                      value={firstName}
Value should be `LastName`

2022-07-30 21:37 UTC, taiwoAkindele commented on src/components/PaystackIntegration.jsx
> +                      onChange={(e) => setFirstName(e.target.value)}
onChange should be `setLastName(e.target.value)`

2022-07-30 21:37 UTC, taiwoAkindele commented on src/components/PaystackIntegration.jsx
> +                        <MenuItem value={10}>Bachelor's Degree</MenuItem>
change `value` to something more distinct, this clashes with that of `academic qualifications` fields and one field will end up controlling the other.

2022-07-30 22:10 UTC, Vinyl-Davyl commented on src/components/PaystackIntegration.jsx
> -        setAmount(res.data.data[0].price)
Ohh, thought it wasn't in use.
Resolved!!

2022-07-30 22:15 UTC, Vinyl-Davyl commented on src/components/PaystackIntegration.jsx
> +                      onChange={(e) => setFirstName(e.target.value)}
Yh 
Mistake Resolved!!

2022-07-30 22:47 UTC, taiwoAkindele approved these changes

2022-07-31 13:58 UTC, merged