facebook pixel integration
Zummit-Africa-Inc/Web-Page-FE pull request #75
Opened 2022-08-19 08:43 UTC by pablo-clueless

2022-08-19 09:20 UTC, PhilemonBrain commented on src/Section/AIinAction.js
> +    ReactPixel.trackCustom('Test AI')
why custom tracking? @pablo-clueless

2022-08-19 14:55 UTC, taiwoAkindele requested changes

2022-08-19 14:55 UTC, taiwoAkindele commented on src/components/Popup.jsx
> +         <Button onClick={() => setOpenPopup(false)} sx={{position:'absolute',top:'15%'}}>
the position here renders the button invisible as the user will not be able to see it on larger screens and also on small screen it places it on the inputfield.

2022-08-19 15:08 UTC, PhilemonBrain approved these changes

2022-08-19 15:09 UTC, merged

2022-08-20 12:13 UTC, pablo-clueless commented on src/components/Popup.jsx
> +         <Button onClick={() => setOpenPopup(false)} sx={{position:'absolute',top:'15%'}}>
It will be fixed soon.